### ISSUE TITLE
Revert it

### ISSUE THREAD

**Issue by 5quirre1** [Freakybob-Team/Freakybob.site#19]
We need the index.html, index.css, and index.js before I did all the stuff that made it look weird. plzzz help greg

**Comment by wish13yt** [comment]
Used the wrong commit oopsie :3

**Comment by wish13yt** [comment]
Fixed in https://github.com/Freakybob-Team/Freakybob.site/commit/d47705a36edd9d1d6f5a3d2ca9acf55bd1208c7f
