### ISSUE TITLE
image-gallery freaky image 👅 

### ISSUE THREAD

**Issue by 5quirre1** [Freakybob-Team/Freakybob.site#5]
![dehydratedfreakybob](https://github.com/user-attachments/assets/48f38197-28ad-4292-9ac2-25e548ab66ee)
It would be so freaky if we put this in :3

**Comment by sspruce2** [comment]
it would be

**Comment by wish13yt** [comment]
this should be in [Freakybob-Team/image-gallery](https://github.com/Freakybob-Team/image-gallery), but I'll let it slide this time.

**Comment by wish13yt** [comment]
added in https://github.com/Freakybob-Team/image-gallery/commit/294ef75ac564310c5aa4f5704a702536edae539f
